config/routes.rb
Rails.application.routes.draw do
  get 'words/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get '/profile', to: 'users#show'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new' 
  get '/dashboard', to: 'users#dashboard'
  get '/settings', to: 'users#edit'
  post '/signup',  to: 'users#create'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do 
    resources :categories do
      resources :words
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,  only: [:create, :destroy]
  resources :users
  resources :categories
  resources :words, only: [:index]
  resources :activities do 
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices , dependent: :destroy
  accepts_nested_attributes_for :choices
  default_scope -> { order(created_at: :desc) }
  # validates :category_id, presence: true
  validates :word, presence: true, length: { maximum: 15 }
  
  def answer_right
    choices.find_by(correct: true).try(:content)
  end
end 

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :index, :edit, :update, :destroy]
  
  def index
    @category = Category.find_by_id(params[:category_id])
    @words = @category.words.paginate(page: params[:page], :per_page => 10)
  end

  def new
    @word = Word.new
    3.times { @word.choices.build }
  end

  def create
    @category = Category.find_by_id(params[:category_id]) 
    @word = @category.words.build(word_params)
    if @word.save
      flash[:success] = "Word created!"
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by_id(params[:category_id])
    @word = Word.find(params[:id])
  end
      
  def update
    @word = Word.find(params[:id])
    @choices = @word.choices
    if @word.update_attributes(word_params)
      flash[:success] = "Word updated!"
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def destroy
    Word.find(params[:id]).destroy
    flash[:success] = "Word deleted!"
    redirect_to admin_category_words_url
  end  

  private
    def word_params
      params.require(:word).permit(:word, choices_attributes: [:content, :correct, :id])
    end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user, only: [:index]  
  def index
     @answers = current_user.group_answer(params).paginate(page: params[:page], per_page:10)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/admin/words/_form.html.erb
<%= render 'shared/error3_messages' , object: f.object%>

    <div class="form-label-group">
        <%= f.text_field :word, class: 'form-control' %>
        <%= f.label :word %>
    </div>
    
    <%= f.fields_for :choices do |a| %>
        <div class="form-label-group">
            <div class = "row">
                <div class = "col-md-6">
                    <%= a.text_field :content, class: 'form-control' %>
                </div>
                <div class = "col-md-6 choice">
                   <h5>Choice<h5>
                   <%= a.check_box :correct, class:"choice_taken"%>
                   <%= a.label :correct %>
                </div>
            </div>
        </div>
<% end %>
<%= f.submit yield(:button_text), class: "btn btn-primary" , id: "sub_button"%>

app/views/admin/words/_word.html.erb
<tr id="word-<%= word.id %>">
    <td><%= word.word %></td>
    <td><%= word.answer_right || "No answer" %></td>
    <td><%= link_to "Edit", edit_admin_category_word_path(@category, word), class: "btn btn-warning btn-sm"%> <%= link_to "Delete", [:admin, @category, word], method: :delete,
    data: { confirm: "You sure?" },  class: "btn btn-danger btn-sm" %> </td>
</tr>

app/views/admin/words/edit.html.erb
<% provide(:title, 'Edit Word') %>
<% provide(:button_text, 'Save changes') %>
<div class="col-lg-10 col-xl-9 mx-auto">
    <div class="card card-signin flex-row my-5">
        <div class="card-body">
        <h5 class="card-title text-left">Update word | <%=@word.word%></h5>
                <%= form_for([:admin, @category, @word]) do |f| %>
                    <%= render partial: 'form', locals: { f: f } %>
                <% end %>
        </div>
    </div>
</div>

<script type="text/javascript">
$('.choice_taken').on('change', function() {
    $('.choice_taken').not(this).prop('checked', false);
});

$('.choice_taken').click(function () {
    if ($(this).is(':checked')) {
        $('#sub_button').removeAttr('disabled'); 

    } else {
        $('#sub_button').attr('disabled', true); 
    }
});

</script>

app/views/admin/words/index.html.erb
<br><br>
<div class="col-lg-12 mx-auto">
    <div class="card card-signin col-lg-12 mx-auto">
        <br><br>
        <div class = "row">
            <div class = "col">
            <h3 class="card-title text-left">Category | <%= @category.title %></h3>      
            </div>

            <div class="d-flex flex-row-reverse">
                <div class="p-2"><%= link_to "Back", admin_categories_path, class: "btn btn-info btn-md" %></div>
                <div class="p-2"><%= link_to "Add word", new_admin_category_word_path(@category), class: "btn btn-secondary btn-md" %></div>
            </div>
        </div>

        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">Words</th>
                    <th scope="col">Answer</th>
                    <th scope="col">Action</th>
                </tr>
            </thead>
            <tbody>
            <%if @words.any? %>
            <%= render @words %>
            <% else %>
                <tr>
                   <td></td>
                   <td>No words in this category yet</td> 
                   <td></td>
                </tr>
            <% end %>
            </tbody>
        </table>
        <div class="mx-auto" style="width: 300px;">
            <%= will_paginate @words%>
        <div class="mx-auto" style="width: 300px;">
    <div class="card card-signin flex-row my-5">
</div>

app/views/admin/words/new.html.erb
<% provide(:title, 'New Word') %>
<% provide(:button_text, 'Submit') %>
<div class="col-lg-10 col-xl-9 mx-auto">
    <div class="card card-signin flex-row my-5">
        <div class="card-body">
            <h5 class="card-title text-left"> Add word</h5>
            <%= form_for([:admin_category, @word]) do |f| %>
                <%= render partial: 'form', locals: { f: f } %>
            <% end %>
        </div>
    </div>
</div>

<script type="text/javascript">
$('.choice_taken').on('change', function() {
    $('.choice_taken').not(this).prop('checked', false);
});

$('.choice_taken').change(function () {
    $('#sub_button').prop("disabled", !this.checked);
}).change()

</script>