config/routes.rb
Rails.application.routes.draw do
  get 'words/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get '/profile', to: 'users#show'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new' 
  get '/dashboard', to: 'users#dashboard'
  get '/settings', to: 'users#edit'
  post '/signup',  to: 'users#create'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do 
    resources :categories do
      resources :words
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,  only: [:create, :destroy]
  resources :users
  resources :categories
  resources :words, only: [:index]
  resources :activities do 
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  acts_as_voter
  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  has_many :lessons
  has_many :words, through: :lessons
  has_many :answers, through: :lessons
  has_many :categories, through: :lessons
  has_many :activities
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :passive_relationships, class_name:  "Relationship",
                                   foreign_key: "followed_id",
                                   dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower
  validates :password, presence: true, length: { minimum: 6 },allow_nil: true
  mount_uploader :picture, PictureUploader

  def lesson(category)
    lesson_exist = self.lessons.find_by(category: category)
  end

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def group_answer(params)
    if params[:category].present?
      answers.where("lessons.category_id = ?", params[:category])
    else
      answers
    end
  end

  def follow(other_user)
    following << other_user
  end

  def unfollow(other_user)
    following.delete(other_user)
  end

  def following?(other_user)
    following.include?(other_user)
  end

  def posts
    Activity.where("user_id IN (?) OR user_id = ?", following_ids, self.id)
  end

  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/users_controller.rb
  class UsersController < ApplicationController
    before_action :logged_in_user, only: [:create, :index, :edit, :update, :dashboard, :show, :new] 
    def index
      @users = User.where.not(id: current_user.id).paginate(page: params[:page], per_page:8)
    end

    def show
      @user = User.find(params[:id])
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        log_in @user
        flash[:success] = "Welcome to the E-Learning System"
        redirect_to @user
      else
        render 'new'
      end
    end

    def edit
      @user = current_user
    end

    def update
      @user = current_user

      if @user.update_attributes(user_params)
        flash[:success] = "Account information updated!"
        redirect_to dashboard_url
      else
        render 'edit'
      end
    end

    def dashboard
      @posts = current_user.posts.paginate(page: params[:page], per_page:8)
    end
    private 

      def user_params
        params.require(:user).permit(:name, :email, :password, :password_confirmation, :picture)
      end
  end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_follow.html.erb
<%= form_for(current_user.active_relationships.build,  remote: true) do |f| %>
    <div><%= hidden_field_tag :followed_id, @user.id %></div>
    <%= f.submit "Follow", class: "btn btn-warning btn-sm" %>
  <% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
    <div id="follow_form_<%= @user.id%>">
        <% if current_user.following?(@user) %>
            <%= render 'unfollow'%>
        <% else %>
            <%= render 'follow'%>
        <% end %>
    </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
html: { method: :delete },  remote: true) do |f| %>
    <%= f.submit "Unfollow", class: "btn btn-danger btn-sm" %>
<% end %>

app/views/users/dashboard.html.erb
<%= provide(:page_title, "Dashboard") %>
<br><br>
<div class = "row">
    <div class = "col-sm-4">

        <div class="card">
            <div class="card-body">
                <div class="text-center">
                        <%if current_user.picture? %>
                            <%= image_tag(current_user.picture.url,  size:"180x180",class: "rounded-pill") %>
                        <% else %>
                            <%= image_tag("user.png",  size:"180x180",class: "rounded-pill") %>
                        <% end %>

                    <h4><%= current_user.name %></h4>
                    <div><%= current_user.email %></div>

                    <div class="mt-3">
                        <%= link_to "View profile", user_path(current_user), class: "btn btn-sm btn-secondary text-white" %>
                        <%= link_to "Update profile", settings_path, class: "btn btn-sm btn-info text-white" %>
                    </div>
                </div>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-body">
                <div class="text-center">
                    <div class="d-inline-block mr-2">
                        <h4><%= current_user.following.count %></h4> following
                    </div>
                    <div class="d-inline-block">
                        <h4><%= current_user.followers.count %></h4> followers
                    </div>
                </div>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-body">
                <div class = "text-center">
                    <h4><%= current_user.words.count%><%= link_to "words learned", words_path , class: 'btn btn-info btn-block p-3'%></h4>
                </div>
            </div>
        </div>
    </div>

    <div class = "col-md-8">
        <div class="card">
            <h5 class="card-header">Activity Feed</h5>
            <div class="card-body">
            <%if @posts.exists?%>
               <% @posts.each do |post|%>
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex">
                            <% @user = post.user %>
                            <%if post.action.is_a?(Lesson)%>
                                <%= render partial: 'activities/lesson_activity', locals: { post: post } %>
                            <%else%>
                                <%= render partial: 'activities/relationship_activity', locals: { post: post } %>
                            <%end%>
                        </div>
                    </div>
                </div>
               <% end %>
               <div class="mx-auto" style="width: 400px;">
                    <%= will_paginate @posts%>
               </div>
            <%else%>
                <center><h5>No activity yet</h5></center>
            <%end%>
            </div>
            
        </div>
    </div>
</div>

app/views/users/edit.html.erb
<br>
<div class="col d-flex justify-content-center">
    <div class="card w-50">
        <div class="card-header">
            <h4 class="card-title">Settings</h4>
        </div>
        <div class="card-body">
            <div class = "row">
                <div class= "col">
                    <%= form_for(@user) do |f|%>
                        <%= render 'shared/error_messages' , object: f.object%>
                        <div class="form-label-group">
                            <div class="text-center">
                            <%if @user.picture? %>
                                <%= image_tag(@user.picture.url, size:"150x150")%>
                            <%else%>
                                <%= image_tag("user.png", size:"150x150")%>
                            <%end%>
                            </div>
                            <br>
                            <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png', class: 'form-control' %>
                        </div>

                        
                        <div class="form-label-group">
                            <%= f.text_field :name, class: 'form-control' %>
                            <%= f.label :name %>
                        </div>

                        <div class="form-label-group">
                            <%= f.email_field :email, class: 'form-control' %>
                            <%= f.label :email %>
                        </div>

                        <div class="form-label-group">
                            <%= f.password_field :password, class: 'form-control' %>
                            <%= f.label :password%>
                        </div>

                        <div class="form-label-group">
                            <%= f.password_field :password_confirmation, class: 'form-control' %>
                            <%= f.label :password_confirmation%>
                        </div>

                        <div class="text-center">
                            <%= f.submit "Update changes", class: "btn btn-primary " %>
                        </div>
                    <%end%>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'Users') %>
<br>
<div class="row">
    <%if @users.any? %>
        <% @users.each do |user| %>
            
            <div class="col-sm-6">
                <div class="card">
                    <div class="card-body">
                        <div class="d-flex">
                            <div class="p-2">
                                <%if user.picture? %>
                                    <%= image_tag(user.picture.url,  size:"100x100",class: "rounded-pill") %>
                                <% else %>
                                    <%= image_tag("user.png",  size:"100x100",class: "rounded-pill") %>
                                <% end %>
                            </div>

                            <div class="p-2"><h5 class="card-title"><%= link_to user.name, user_path(user) %></h5></div>
                            <div class="ml-auto p-2">
                                <% @user = user %>
                                <%= render 'follow_form' if logged_in?%>  
                            </div>
                        </div>
                    </div>
                </div>
                <br><br>
            </div>
        <%end%>
    <%else%>
      <h5><center>No existing users yet</center></h5>
    <%end%>
    <div class="mx-auto" style="width: 300px;">
        <%= will_paginate %>
    </div>
</div>

app/views/users/new.html.erb
    <% provide(:title, 'Sign up') %>
    <div class="row">
        <div class="col-lg-10 col-xl-9 mx-auto">
            <div class="card card-signin flex-row my-5">
                <div class="card-img-left d-none d-md-flex">
                </div>
                <div class="card-body">
                    <h5 class="card-title text-center">Register</h5>
                        <%= form_for(@user, url: signup_path) do |f| %>
                            <%= render 'shared/error_messages' , object: f.object%>

                            <div class="form-label-group">
                                <%= f.text_field :name, class: 'form-control' %>
                                <%= f.label :name %>
                            </div>

                            <div class="form-label-group">
                                <%= f.email_field :email, class: 'form-control' %>
                                <%= f.label :email %>
                            </div>

                            <div class="form-label-group">
                                <%= f.password_field :password, class: 'form-control' %>
                                <%= f.label :password %>
                            </div>

                            <div class="form-label-group">
                                <%= f.password_field :password_confirmation, class: 'form-control' %>
                                <%= f.label :password_confirmation, "Confirmation" %>
                            </div>
                            <%= f.submit "Create my account", class: "btn btn-primary" %>
                        <% end %>
                        <a class="d-block text-center mt-2 small" href="#">Sign In</a>
                        <hr class="my-4">
                </div>
            </div>
        </div>
    </div>

app/views/users/show.html.erb
<%= provide(:page_title, @user.name) %>
<br><br>
<div class = "row">
    <div class = "col-sm-4">
        <div class="card">
            <div class="card-body">
                <div class="text-center">
                        <%if @user.picture? %>
                            <%= image_tag(@user.picture.url,  size:"100x100",class: "rounded-pill") %>
                        <% else %>
                            <%= image_tag("user.png",size:"100x100",class: "rounded-pill") %>
                        <% end %>

                    <h4><%= @user.name %></h4>
                    <div><%= @user.email %></div>
                    <%= render 'follow_form' if logged_in?%>    
                </div>
            </div>
        </div>

        <div class="card mt-4">
            <% @user ||= current_user %>
            <div class="card-body">
                <div class="text-center">
                    <div class="d-inline-block mr-2">
                        <h4 id = "following"><%= @user.following.count %></h4> following
                    </div>
                    <div class="d-inline-block">
                        <h4 id = "followers"><%= @user.followers.count %></h4>  followers
                    </div>
                </div>
            </div>
        </div>

        <div class="card mt-4">
            <div class="card-body">
                <div class = "text-center">
                    <h4><%= @user.words.count%></h4>
                    words learned
                </div>
            </div>
        </div>
    </div>

    <div class = "col-md-8">
        <div class="card">
            <h5 class="card-header">Activity Feed</h5>
            <div class="card-body">
                <%if @user.activities.exists?%>
                    <% @user.activities.each do |post|%>
                        <div class="card">
                            <div class="card-body">
                                <div class="d-flex">
                                    <%if post.action.is_a?(Lesson)%>
                                        <%= render partial: 'activities/lesson_activity', locals: { post: post } %>
                                    <%else%>
                                        <%= render partial: 'activities/relationship_activity', locals: { post: post } %>
                                    <%end%>
                                </div>
                            </div>
                        </div>
                    <% end %>
                <%else%>
                    <center><h5>No activity yet</h5></center>
                <%end%>
            </div>
        </div>
    </div>
</div>