config/routes.rb
Rails.application.routes.draw do
  get 'words/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get '/profile', to: 'users#show'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new' 
  get '/dashboard', to: 'users#dashboard'
  get '/settings', to: 'users#edit'
  post '/signup',  to: 'users#create'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do 
    resources :categories do
      resources :words
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,  only: [:create, :destroy]
  resources :users
  resources :categories
  resources :words, only: [:index]
  resources :activities do 
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :category
  has_many :choices , dependent: :destroy
  accepts_nested_attributes_for :choices
  default_scope -> { order(created_at: :desc) }
  # validates :category_id, presence: true
  validates :word, presence: true, length: { maximum: 15 }
  
  def answer_right
    choices.find_by(correct: true).try(:content)
  end
end 

app/controllers/admin/words_controller.rb
class Admin::WordsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy, :index, :edit, :update, :destroy]
  
  def index
    @category = Category.find_by_id(params[:category_id])
    @words = @category.words.paginate(page: params[:page], :per_page => 10)
  end

  def new
    @word = Word.new
    3.times { @word.choices.build }
  end

  def create
    @category = Category.find_by_id(params[:category_id]) 
    @word = @category.words.build(word_params)
    if @word.save
      flash[:success] = "Word created!"
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def edit
    @category = Category.find_by_id(params[:category_id])
    @word = Word.find(params[:id])
  end
      
  def update
    @word = Word.find(params[:id])
    @choices = @word.choices
    if @word.update_attributes(word_params)
      flash[:success] = "Word updated!"
      redirect_to admin_category_words_url
    else
      render 'new'
    end
  end

  def destroy
    Word.find(params[:id]).destroy
    flash[:success] = "Word deleted!"
    redirect_to admin_category_words_url
  end  

  private
    def word_params
      params.require(:word).permit(:word, choices_attributes: [:content, :correct, :id])
    end

end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :logged_in_user, only: [:index]  
  def index
     @answers = current_user.group_answer(params).paginate(page: params[:page], per_page:10)
  end
end

app/helpers/words_helper.rb
module WordsHelper
end

app/views/words/index.html.erb
<%= provide(:page_title, "Dashboard") %>
<br><br>

<div class="container py-5"> 
<div class="row">
    <div class="col-4">
        <div class="card">
            <div class="card-body text-center">
                <%if current_user.picture? %>
                    <%= image_tag(current_user.picture.url,  size:"180x180",class: "rounded-pill") %>
                <% else %>
                    <%= image_tag("user.png",  size:"180x180",class: "rounded-pill") %>
                <% end %>

                <h4><%= current_user.name %></h4>
                <div><%= current_user.email %></div>

                <div class="mt-3">
                    <%= link_to "View profile", user_path(current_user), class: "btn btn-sm btn-secondary text-white" %>
                    <%= link_to "Update profile", settings_path, class: "btn btn-sm btn-info text-white" %>
                </div>               
            </div>
        </div>
    </div>
    <div class="col-8">
        <div class="card">
            <div class="card-header">
                <small><b class="text-uppercase">Words Learned</b></small>
                <span class="float-right"><span class="font-weight-italic"><small><%= link_to "Back to dashboard", dashboard_path %></small></span></span>
            </div>
            <div class="card-body">
                <%= form_tag words_path, method: :get do %>
                    <div class="form-inline">
                        <label class="mr-3" for="category">Category</label>
                        <%= select_tag(:category,
                                    options_from_collection_for_select(current_user.categories, 'id', 'title', params[:category]),
                                    include_blank: "All learned",
                                    class: 'form-control', onchange: "this.form.submit();") %>
                    </div>
                <% end %>    
                <table class="table table-striped">
                <thead>
                  <tr>
                    <th scope="col">Word</th>
                    <th scope="col">Your answer</th>
                    <th scope="col">Correct Answer</th>
                  </tr>
                </thead>
                <tbody>
                <%if @answers.any? %>
                    <% @answers.each do |f|%>
                        <tr>
                            <td><%= f.word.word %></td>
                            <%if f.choice.content == f.word.answer_right%>
                                <td><p class="text-success font-weight-bold"><%= f.choice.content%></p></td>
                                <td> </td>
                            <%else%>
                                <td><p class="text-danger font-weight-bold"><%= f.choice.content%></p></td>
                                <td><%= f.word.answer_right%></td>
                            <%end%>
                        </tr>
                    <%end%>
                <%else%>
                    <tr>You have not answered any lessons yet
                        <td></td>
                        <td>You have not answered any lessons yet</td>
                        <td></td>
                    </tr>

                <%end%>
                </tbody>
              </table>
              <div class="mx-auto" style="width: 500px;">
                <%= will_paginate @answers %>
              </div>
            </div>
        </div>
    </div>
</div>
</div>