config/routes.rb
Rails.application.routes.draw do
  get 'words/new'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'sessions#new'
  get '/profile', to: 'users#show'
  get '/signup', to: 'users#new'
  get '/login', to: 'sessions#new' 
  get '/dashboard', to: 'users#dashboard'
  get '/settings', to: 'users#edit'
  post '/signup',  to: 'users#create'
  post '/login', to: 'sessions#create'
  
  delete '/logout', to: 'sessions#destroy'

  namespace :admin do 
    resources :categories do
      resources :words
    end
  end

  resources :lessons do
    resources :answers
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships,  only: [:create, :destroy]
  resources :users
  resources :categories
  resources :words, only: [:index]
  resources :activities do 
    member do
      put "like", to: "activities#upvote"
      put "dislike", to: "activities#downvote"
    end
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :words, dependent: :destroy 
  has_many :lessons, dependent: :destroy
  validates :description, presence: true
  default_scope -> { order(created_at: :desc) }
  validates :title, presence: true
  
  def self.has_words
    Category.where(:id => Word.select(:category_id).map(&:category_id))
  end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
before_action :logged_in_user, only: [:create, :destroy, :index, :edit, :update, :destroy]

def index
  @categories = Category.paginate(page: params[:page], :per_page => 10)
end
def new
  @category = Category.new
end
    
def create
  @category = Category.new(category_params)
  if @category.save
    flash[:success] = "Category added!"
    redirect_to admin_categories_url
  else
    render 'new'
  end
end
    
def edit
  @category = Category.find(params[:id])
end
    
def update
  @category = Category.find(params[:id])
  if @category.update_attributes(category_params)
    flash[:success] = "Category updated!"
    redirect_to admin_categories_url
  else
    render 'edit'
  end
end
    
def destroy
  Category.find(params[:id]).destroy
  flash[:success] = "Category deleted!"
  redirect_to admin_categories_url
end
    
  private 
    def category_params
      params.require(:category).permit(:title, :description)
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    before_action :logged_in_user, only: [:index]
    def index
        @categories = Category.paginate(page: params[:page], per_page:8).has_words
        if params[:learned] == "1"
            @categories = current_user.categories.paginate(page: params[:page], per_page:8)
        elsif params[:learned] == "0"
            @categories = @categories.where.not(id: current_user.category_ids).paginate(page: params[:page], per_page:8)
        end
    end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/edit.html.erb
<% provide(:title, 'Edit Category') %>
<div class="col-lg-10 col-xl-9 mx-auto">
    <div class="card card-signin flex-row my-5">
        <div class="card-body">
        <h5 class="card-title text-center">Update category</h5>
            <%= form_for :category, url: {action: "update"}, :method => :PATCH do |f| %>
                <%= render 'shared/error2_messages' , object: f.object%>

                <div class="form-label-group">
                    <%= f.text_field :title, class: 'form-control' %>
                    <%= f.label :title %>
                </div>

                <div class="form-label-group">
                    <%= f.text_field :description, class: 'form-control' %>
                    <%= f.label :description %>
                </div>
                <%= f.submit "Save changes", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>

app/views/admin/categories/index.html.erb
<% provide(:title, 'Category List') %>
<br><br>
<div class="col-lg-12 mx-auto">
<div class="card card-signin col-lg-12 mx-auto">
<br><br>
<div class = "row">
    <div class = "col">
        <h3>Categories</h3>
    </div>

    <div class = "col">
        <%= link_to "Add category", new_admin_category_path, class: "btn btn-secondary btn-md" %>
    </div>
</div>

<table class="table table-striped">
    <thead>
        <tr class="d-flex">
            <th class="col-3">Title</th>
            <th class="col-4">Description</th>
            <th class="col-2">No. of words</th>
            <th class="col-3">Actions</th>
        </tr>
    </thead>
    <tbody>
        <%if @categories.exists?%>
            <% @categories.each do |category| %>
                <tr class="d-flex">
                    <td class="col-3"><%= category.title %></td>
                    <td class="col-4"><%= category.description %></td>
                    <td class="col-2"><%= category.words.count %></td>
                    <td class="col-3"><%= link_to "Show words", admin_category_words_path(category), class: "btn btn-primary btn-sm" %> <%= link_to "Edit", edit_admin_category_path(category), class: "btn btn-warning btn-sm"%> <%= link_to "Delete", admin_category_path(category), method: :delete,
                    data: { confirm: "You sure?" },  class: "btn btn-danger btn-sm" %> </td>
                </tr>
            <% end %>
        <%else%>
            <tr>No categories yet</tr>
        <%end%>
    </tbody>
</table>
<div class="mx-auto" style="width: 300px;">
    <%= will_paginate %>
</div>
<div class="card card-signin flex-row my-5">
</div>

app/views/admin/categories/new.html.erb
<div class="col-lg-10 col-xl-9 mx-auto">
    <div class="card card-signin flex-row my-5">
        <div class="card-body">
            <h5 class="card-title text-center">Add category</h5>
            <%= form_for([:admin, @category]) do |f| %>
                <%= render 'shared/error2_messages' , object: f.object%>

                <div class="form-label-group">
                    <%= f.text_field :title, class: 'form-control' %>
                    <%= f.label :title %>
                </div>

                <div class="form-label-group">
                    <%= f.text_field :description, class: 'form-control' %>
                    <%= f.label :description %>
                </div>
                <%= f.submit "Submit", class: "btn btn-primary" %>
            <% end %>
        </div>
    </div>
</div>